/*
 * HPSM
 *
 * This is the SCANOSS HPSM API.
 *
 * API version: 1.0.0
 * Contact: apiteam@swagger.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type HpsmRespItem struct {
	MD5 string `json:"MD5,omitempty"`

	Snippets []Snippet `json:"snippets,omitempty"`

	Message string `json:"message,omitempty"`
}
