/*
 * HPSM
 *
 * This is the SCANOSS HPSM API.
 *
 * API version: 1.0.0
 * Contact: apiteam@swagger.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type HpsmReqItem struct {
	MD5 string `json:"MD5,omitempty"`

	Snippets []Snippet `json:"snippets,omitempty"`

	Threshold int32 `json:"threshold,omitempty"`

	Hashes []uint8 `json:"hashes,omitempty"`
}
