/*
 * HPSM
 *
 * This is the SCANOSS HPSM API.
 *
 * API version: 1.0.0
 * Contact: apiteam@swagger.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Snippet struct {
	Local *ModelRange `json:"local,omitempty"`

	Remote *ModelRange `json:"remote,omitempty"`
}
