// file.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.6.1
// source: hpsm.proto

package hpsm

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HPSMRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Md5  string `protobuf:"bytes,2,opt,name=md5,proto3" json:"md5,omitempty"`
}

func (x *HPSMRequest) Reset() {
	*x = HPSMRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hpsm_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HPSMRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HPSMRequest) ProtoMessage() {}

func (x *HPSMRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hpsm_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HPSMRequest.ProtoReflect.Descriptor instead.
func (*HPSMRequest) Descriptor() ([]byte, []int) {
	return file_hpsm_proto_rawDescGZIP(), []int{0}
}

func (x *HPSMRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *HPSMRequest) GetMd5() string {
	if x != nil {
		return x.Md5
	}
	return ""
}

type RangeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Local   string `protobuf:"bytes,1,opt,name=local,proto3" json:"local,omitempty"`
	Remote  string `protobuf:"bytes,2,opt,name=remote,proto3" json:"remote,omitempty"`
	Matched string `protobuf:"bytes,3,opt,name=matched,proto3" json:"matched,omitempty"`
}

func (x *RangeResponse) Reset() {
	*x = RangeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hpsm_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RangeResponse) ProtoMessage() {}

func (x *RangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hpsm_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RangeResponse.ProtoReflect.Descriptor instead.
func (*RangeResponse) Descriptor() ([]byte, []int) {
	return file_hpsm_proto_rawDescGZIP(), []int{1}
}

func (x *RangeResponse) GetLocal() string {
	if x != nil {
		return x.Local
	}
	return ""
}

func (x *RangeResponse) GetRemote() string {
	if x != nil {
		return x.Remote
	}
	return ""
}

func (x *RangeResponse) GetMatched() string {
	if x != nil {
		return x.Matched
	}
	return ""
}

var File_hpsm_proto protoreflect.FileDescriptor

var file_hpsm_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x68, 0x70, 0x73, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x68, 0x70,
	0x73, 0x6d, 0x67, 0x70, 0x72, 0x70, 0x63, 0x22, 0x33, 0x0a, 0x0b, 0x48, 0x50, 0x53, 0x4d, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x64,
	0x35, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x64, 0x35, 0x22, 0x57, 0x0a, 0x0d,
	0x52, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x6f,
	0x63, 0x61, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d,
	0x61, 0x74, 0x63, 0x68, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x61,
	0x74, 0x63, 0x68, 0x65, 0x64, 0x32, 0x49, 0x0a, 0x04, 0x48, 0x50, 0x53, 0x4d, 0x12, 0x41, 0x0a,
	0x0d, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x48, 0x61, 0x73, 0x68, 0x65, 0x73, 0x12, 0x16,
	0x2e, 0x68, 0x70, 0x73, 0x6d, 0x67, 0x70, 0x72, 0x70, 0x63, 0x2e, 0x48, 0x50, 0x53, 0x4d, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x68, 0x70, 0x73, 0x6d, 0x67, 0x70, 0x72,
	0x70, 0x63, 0x2e, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x42, 0x12, 0x5a, 0x10, 0x73, 0x63, 0x61, 0x6e, 0x6f, 0x73, 0x73, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x68, 0x70, 0x73, 0x6d, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_hpsm_proto_rawDescOnce sync.Once
	file_hpsm_proto_rawDescData = file_hpsm_proto_rawDesc
)

func file_hpsm_proto_rawDescGZIP() []byte {
	file_hpsm_proto_rawDescOnce.Do(func() {
		file_hpsm_proto_rawDescData = protoimpl.X.CompressGZIP(file_hpsm_proto_rawDescData)
	})
	return file_hpsm_proto_rawDescData
}

var file_hpsm_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_hpsm_proto_goTypes = []interface{}{
	(*HPSMRequest)(nil),   // 0: hpsmgprpc.HPSMRequest
	(*RangeResponse)(nil), // 1: hpsmgprpc.RangeResponse
}
var file_hpsm_proto_depIdxs = []int32{
	0, // 0: hpsmgprpc.HPSM.ProcessHashes:input_type -> hpsmgprpc.HPSMRequest
	1, // 1: hpsmgprpc.HPSM.ProcessHashes:output_type -> hpsmgprpc.RangeResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_hpsm_proto_init() }
func file_hpsm_proto_init() {
	if File_hpsm_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_hpsm_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HPSMRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hpsm_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RangeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_hpsm_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_hpsm_proto_goTypes,
		DependencyIndexes: file_hpsm_proto_depIdxs,
		MessageInfos:      file_hpsm_proto_msgTypes,
	}.Build()
	File_hpsm_proto = out.File
	file_hpsm_proto_rawDesc = nil
	file_hpsm_proto_goTypes = nil
	file_hpsm_proto_depIdxs = nil
}
