name: Release
# Build and attach supported artifacts a draft release tag

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    container: debian:bullseye
    steps:
      - name: Setup build tools
        run: |
          apt-get update
          apt-get install build-essential ca-certificates git -y 
          update-ca-certificates
          git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Get tags to allow build script to get build version

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Build
        run: |
          make build_amd

      - name: Unit Test
        run: make unit_test

      - name: Package
        run: |
          make package_amd

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: |
            hpsm_linux-amd64_${{ github.ref_name }}-1.tgz